# Generated by Django 4.1.6 on 2023-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonName', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('EmployeeID', models.IntegerField()),
            ],
        ),
    ]
