# Generated by Django 4.1.6 on 2023-02-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_room_delete_location_rename_location_sensors_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='personincharge',
            name='EmployeeRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.room'),
        ),
        migrations.AddField(
            model_name='temphumid',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.room'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.room'),
        ),
    ]
