# Generated by Django 4.1.6 on 2023-02-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_personincharge_employeeroom_temphumid_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='person',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.personincharge'),
        ),
    ]
