# Generated by Django 4.1.6 on 2023-02-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_alter_temphumid_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('value1', models.CharField(max_length=30)),
                ('value2', models.CharField(max_length=30)),
                ('reading_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='temphumid',
            name='room',
        ),
        migrations.RemoveField(
            model_name='temphumid',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='SensorName',
        ),
        migrations.RemoveField(
            model_name='sensors',
            name='person',
        ),
        migrations.AddField(
            model_name='sensors',
            name='PIC',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sensors',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='room',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='PersonInCharge',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='TempHumid',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensors'),
        ),
    ]
